# https://squidfunk.github.io/mkdocs-material/getting-started
# https://squidfunk.github.io/mkdocs-material/reference/admonitions
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

site_name: Using Pre-Built packages of gRPC using CONAN
site_description: Instruction and documentation to set up gRPC using CONAN Packages
site_author: Thomas Hochstrasser
site_url: https://github.com/thommyho/Cpp-gRPC-Linux-x64-ARM-PreBuilts

repo_name: thommyho/Cpp-gRPC-Linux-x64-ARM-PreBuilts
repo_url: https://github.com/thommyho/Cpp-gRPC-Linux-x64-ARM-PreBuilts
edit_uri: ""

docs_dir: docs

theme:
  logo: _assets/logo.svg
  favicon: _assets/favicon.ico
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: overrides

  font:
    text: "arial, sans-serif"
    code: monospace
  features:
    # - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    # - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

extra_css:
  - _assets/user.css

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - def_list
  - attr_list
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs

plugins:
  - search:
      lang: en

nav:
  - Home:
      - Information: index.md
      - Release-Table: list.md
              
  - Version:
      - v1.50.1:
          - gRPC: packages/v1_50_1/grpc.md
          - Dependency-Table: packages/v1_50_1/table.html
          - Dependencies-Packages:
              - abseil: packages/v1_50_1/abseil.md
              - c-ares: packages/v1_50_1/c-ares.md
              - googleapis: packages/v1_50_1/googleapis.md
              - grpc-proto: packages/v1_50_1/grpc-proto.md
              - openssl: packages/v1_50_1/openssl.md
              - protobuf: packages/v1_50_1/protobuf.md
              - re2: packages/v1_50_1/re2.md
      - v1.47.1:
          - gRPC: packages/v1_47_1/grpc.md
          - Dependency-Table: packages/v1_47_1/table.html
          - Dependencies-Packages:
              - abseil: packages/v1_47_1/abseil.md
              - c-ares: packages/v1_47_1/c-ares.md
              - googleapis: packages/v1_47_1/googleapis.md
              - grpc-proto: packages/v1_47_1/grpc-proto.md
              - openssl: packages/v1_47_1/openssl.md
              - protobuf: packages/v1_47_1/protobuf.md
              - re2: packages/v1_47_1/re2.md
              - zlib: packages/v1_47_1/zlib.md  
      - v1.46.3:
          - gRPC: packages/v1_46_3/grpc.md
          - Dependency-Table: packages/v1_46_3/table.html
          - Dependencies-Packages:
              - abseil: packages/v1_46_3/abseil.md
              - c-ares: packages/v1_46_3/c-ares.md
              - googleapis: packages/v1_46_3/googleapis.md
              - grpc-proto: packages/v1_46_3/grpc-proto.md
              - openssl: packages/v1_46_3/openssl.md
              - protobuf: packages/v1_46_3/protobuf.md
              - re2: packages/v1_46_3/re2.md
              - zlib: packages/v1_46_3/zlib.md
